sudo: required

services:
 - docker

language: node_js
node_js:
 - "10.12.0"
cache: npm

git:
  depth: 3

env:
 - NODE_ENV=development

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential

install:
 - npm install

script:
 - eslint . --quiet
