module.exports = {
	GATEWAY: {
		VERSION: 6,
		OPCODES: {
			DISPATCH: 0,
			HEARTBEAT: 1,
			IDENTIFY: 2,
			STATUS_UPDATE: 3,
			VOICE_STATE_UPDATE: 4,
			VOICE_SERVER_PING: 5,
			RESUME: 6,
			RECONNECT: 7,
			REQUEST_GUILD_MEMBERS: 10,
			INVALID_SESSION: 9,
			HELLO: 10,
			HEARTBEAT_ACK: 11
		},
		CLOSE_CODES: {
			UNKNOWN: 4000,
			UNKNOWN_OPCODE: 4001,
			DECODE_ERROR: 4002,
			NOT_AUTHENTICATED: 4003,
			AUTHENTICATION_FAILED: 4004,
			ALREADY_AUTHENTICATED: 4005,
			INVALID_RESUME_SEQUENCE: 4007,
			RATE_LIMITED: 4008,
			SESSION_TIMEOUT: 4009,
			INVALID_SHARD: 4010,
			SHARDING_REQUIRED: 4011
		}
	}
};
